let 
    	/* The Monday.com API dated 2023-10 changed the way rows of data are returned from boards.  You now have to call for 1 page of data
    	at a time and also request the cursor which points to the next page of data.  If the cursor is null there are no more pages of data.
    	The maximum number of rows per page is configurable with the maximum allow of 100 rows of data.  The following query attempts to 
    	request five pages of 100 rows of data.  If you expect more than 500 rows of data then additional page requests need to be added below. */
    	
    	
    	/* Define the Monday.com board ID number then call the GetBoard_1stPage function to return the first 100 rows of data */
    	/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
    	/* Assign the value found in the Column1.items_page.cursor column to the 2nd_page_cursor variable */
    
    BoardID = 1234567890,
    #"1st_Page_Table" = GetBoard_1stPage(BoardID),
    #"1st_Page_Table_Updated" = Table.ReplaceValue(#"1st_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"2nd_page_cursor" = #"1st_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 2nd_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 3rd_page_cursor variable */


    #"2nd_Page_Table" = if #"2nd_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"2nd_page_cursor") else EmptyBoardTable(),
    #"2nd_Page_Table_Updated" = Table.ReplaceValue(#"2nd_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"3rd_page_cursor" = #"2nd_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 3rd_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 4th_page_cursor variable */


    #"3rd_Page_Table" = if #"3rd_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"3rd_page_cursor") else EmptyBoardTable(),
    #"3rd_Page_Table_Updated" = Table.ReplaceValue(#"3rd_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"4th_page_cursor" = #"3rd_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 4th_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 5th_page_cursor variable */


    #"4th_Page_Table" = if #"4th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"4th_page_cursor") else EmptyBoardTable(),
    #"4th_Page_Table_Updated" = Table.ReplaceValue(#"4th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"5th_page_cursor" = #"4th_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 5th_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 6th_page_cursor variable */


    #"5th_Page_Table" = if #"5th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"5th_page_cursor") else EmptyBoardTable(),
    #"5th_Page_Table_Updated" = Table.ReplaceValue(#"5th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"6th_page_cursor" = #"5th_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 2nd_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 3rd_page_cursor variable */


    #"6th_Page_Table" = if #"6th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"6th_page_cursor") else EmptyBoardTable(),
    #"6th_Page_Table_Updated" = Table.ReplaceValue(#"6th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"7th_page_cursor" = #"6th_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 3rd_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 4th_page_cursor variable */


    #"7th_Page_Table" = if #"7th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"7th_page_cursor") else EmptyBoardTable(),
    #"7th_Page_Table_Updated" = Table.ReplaceValue(#"7th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"8th_page_cursor" = #"7th_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 4th_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 5th_page_cursor variable */


    #"8th_Page_Table" = if #"8th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"8th_page_cursor") else EmptyBoardTable(),
    #"8th_Page_Table_Updated" = Table.ReplaceValue(#"8th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"9th_page_cursor" = #"8th_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 5th_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 6th_page_cursor variable */


    #"9th_Page_Table" = if #"9th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"9th_page_cursor") else EmptyBoardTable(),
    #"9th_Page_Table_Updated" = Table.ReplaceValue(#"9th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"10th_page_cursor" = #"9th_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 2nd_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 3rd_page_cursor variable */


    #"10th_Page_Table" = if #"10th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"10th_page_cursor") else EmptyBoardTable(),
    #"10th_Page_Table_Updated" = Table.ReplaceValue(#"10th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"11th_page_cursor" = #"10th_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 2nd_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 3rd_page_cursor variable */

    #"11th_Page_Table" = if #"11th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"11th_page_cursor") else EmptyBoardTable(),
    #"11th_Page_Table_Updated" = Table.ReplaceValue(#"11th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    #"12th_page_cursor" = #"11th_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If the 3rd_page_cursor value is not equal to NoMorePages then call the GetBoard_RemainingPages function to get the next page of 100 rows of data */
		/* If the cursor value is NoMorePages then call the EmptyIssuesTable to create an empty table with the correct column names */
		/* Update the Column1.items_page.cursor column if the value is null and replace with NoMorePages  */
		/* Assign the value found in the Column1.items_page.cursor column to the 4th_page_cursor variable */


    #"12th_Page_Table" = if #"12th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"12th_page_cursor") else EmptyBoardTable(),
    #"12th_Page_Table_Updated" = Table.ReplaceValue(#"12th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
   // #"13th_page_cursor" = #"12th_Page_Table_Updated"{0}[Column1.items_page.cursor],

		/* If you need to load more than 500 rows of data then duplicate the three lines above and modify the variable names.  You will also need to add the new variable in the Table.Combine function below */
		/*  E.G.
		
		    #"6th_Page_Table" = if #"6th_page_cursor" <> "NoMorePages" then GetBoard_RemainingPages(#"6th_page_cursor") else EmptyTable(),
    		#"6th_Page_Table_Updated" = Table.ReplaceValue(#"6th_Page_Table",null,"NoMorePages",Replacer.ReplaceValue,{"Column1.items_page.cursor"}),
    		#"7th_page_cursor" = #"6th_Page_Table_Updated"{0}[Column1.items_page.cursor],
		*/


		/* Combine the five tables contained in #"1st_Page_Table_Updated", #"2nd_Page_Table_Updated", #"3rd_Page_Table_Updated", #"4th_Page_Table_Updated", #"5th_Page_Table_Updated" */
		/* Keep all columns except the Column1.items_page.cursor and Column1.items.id columns.  These two columns are not needed.  */
		/* Rename the Column1.items.name to Topic */
		/* Remove the empty rows that were due to any empty tables. */


    Combined_Table1 = Table.Combine({#"1st_Page_Table_Updated", #"2nd_Page_Table_Updated", #"3rd_Page_Table_Updated", #"4th_Page_Table_Updated", #"5th_Page_Table_Updated", #"6th_Page_Table_Updated", #"7th_Page_Table_Updated", #"8th_Page_Table_Updated", #"9th_Page_Table_Updated", #"10th_Page_Table_Updated", #"11th_Page_Table_Updated", #"12th_Page_Table_Updated"}),    // add additional table variables if more than 500 rows of data
    #"Removed Other Columns" = Table.SelectColumns(Combined_Table1,{"Column1.items_page.cursor", "id", "name", "Group", "Subitems", "!", "TITLE", "Hubspot ID", "BRAND", "SALES", "NEW/REVISIONS", "Temp/Perm", "OP VALUE", "REQUEST DATE", "DUE DATE", "LEAD", "EST LEAD", "STATUS", "LEAD TIME", "COMPLETED", "DELIVERABLE", "STD DATE", "WIN/LOSS", "OTIF Notes"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"TITLE", "TITLE.1"}, {"name", "Title"}, {"BRAND", "Brand"}, {"SALES", "Sales"}, {"NEW/REVISIONS", "New/Revisions"}, {"LEAD", "Lead"}, {"DUE DATE", "Due Date"}, {"REQUEST DATE", "Request Date"}, {"EST LEAD", "Est Lead"}, {"STATUS", "Status"}, {"LEAD TIME", "Lead Time"}, {"COMPLETED", "Completed"}, {"DELIVERABLE", "Deliverable"}, {"STD DATE", "Std Date"}, {"WIN/LOSS", "Win/Loss"}, {"OP VALUE", "OP Value"}}),
    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Lead Time (seconds)", each Number.From(Text.BeforeDelimiter([Lead Time], ":"))*3600+ 
(Number.From(Text.BetweenDelimiters([Lead Time],":",":"))*60)+
Number.From(Text.AfterDelimiter([Lead Time],":",1))),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Request Date EST", each DateTime.FromText(Text.Range([Request Date],0,19),[Format="yyyy-MM-dd HH:mm:ss"]) + #duration(0,-5,0,0)),
    #"Filtered Rows" = Table.SelectRows(#"Added Custom1", each [id] <> null and [id] <> ""),
    #"Renamed Columns1" = Table.RenameColumns(#"Filtered Rows",{{"id", "ItemID"}}),
    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns1", "Index", 0, 1, Int64.Type),
    #"Renamed Columns3" = Table.RenameColumns(#"Added Index",{{"Index", "UniqueID"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns3",{{"Due Date", type date}, {"Std Date", type date}, {"Completed", type date}, {"Est Lead", type number}}),
	/*Joining the User table to get the UserName*/
    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Lead"}, Users, {"UserID"}, "Users", JoinKind.LeftOuter),
    #"Expanded Users" = Table.ExpandTableColumn(#"Merged Queries", "Users", {"UserName"}, {"UserName"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Users",{"Lead"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns",{{"UserName", "Lead"}})
in
    #"Renamed Columns2"